image: node:lts-alpine

variables:
  MONGODB_URI: 'mongodb://mongo-test/conduit'
  NODE_ENV: 'integration'

cache:
  key: "build-cache"
  paths:
    - node_modules/

stages:
 - build
 - run
 - test

services:
  - name: mongo:3.4
    alias: mongo-test

build:
  stage: build
  before_script:
    - node -v
    - npm -v
    - cat /etc/hosts
  script:
    - npm install --silent

run:
  stage: run
  script:
    - npm run start

test:
  stage: test
  before_script:
     - npm install -g newman
  script:
    - npm run test
