image: node:lts-alpine

variables:
  MONGODB_URI: 'mongodb://mongo-rwapp-integration/conduit'
  NODE_ENV: 'integration'

cache:
  key: "build-cache"
  paths:
    - node_modules/

stages:
 - build
 - run
 - test

before_script:
  - node -v
  - npm -v

build:
  stage: build
  tags:
    - docker
  script:
    - npm install --silent

run:
  stage: run
  tags:
    - docker
  services:
    - name: mongo:3.4
      alias: mongo-rwapp-integration
  script:
    - npm run start &

test:
  stage: test
  tags:
    - docker
  services:
    - name: mongo:3.4
      alias: mongo-rwapp-integration
  before_script:
    - npm install --silent
    - npm install -g newman
    - npm run start &
  script:
    - npm run test
